INSERT INTO `items` (`name`, `label`, `limit`) VALUES  
    ('jager', 'Jägermeister', 5),
    ('vodka', 'Vodka', 5),
    ('rhum', 'Ron', 5),
    ('whisky', 'Whisky', 5),
    ('tequila', 'Tequila', 5),
    ('martini', 'Martini Blanco', 5),
    ('soda', 'Soda', 5),
    ('jusfruit', 'Zumo', 5),
    ('icetea', 'Te frío', 5),
    ('energy', 'Bebida energética', 5),
    ('drpepper', 'Dr. Pepper', 5),
    ('limonade', 'Limonada', 5),
    ('bolcacahuetes', 'Tazón de cacahuetes', 5),
    ('bolnoixcajou', 'Tazón de anacardo', 5),
    ('bolpistache', 'Tazón de pistachos', 5),
    ('bolchips', 'Plato de patatas fritas', 5),
    ('saucisson', 'Embutidos', 5),
    ('grapperaisin', 'Racimo de uvas', 5),
    ('jagerbomb', 'Jägerbomb', 5),
    ('golem', 'Golem', 5),
    ('whiskycoca', 'Whisky-cola', 5),
    ('vodkaenergy', 'Vodka-energetica', 5),
    ('vodkafruit', 'Vodka-zumo', 5),
    ('rhumfruit', 'Ron-zumo', 5),
    ('teqpaf', "Teq'paf", 5),
    ('rhumcoca', 'Ron-cola', 5),
    ('mojito', 'Mojito', 5),
    ('ice', 'Ice', 5),
    ('mixapero', 'Mezcla de aperitivo', 3),
    ('metreshooter', 'Shooter meter', 3),
    ('jagercerbere', 'Jäger Cerberus', 3),
    ('menthe', 'Bebida de menta', 10)
;