control_key = 83

anims = {
    {dic = "gestures@f@standing@casual", anim = "gesture_bring_it_on", label = "Vamos", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_bye_hard", label = "Fuera", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_come_here_hard", label = "Ven aqui", category = "Gesture"},
    {dic = "misscarstealfinalecar_5_ig_3", anim = "crouchloop", label = "Cubrirse", category = "Misc"},
    {dic = "gestures@f@standing@casual", anim = "gesture_damn", label = "Mierda", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_displeased", label = "Descontento", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_easy_now", label = "Tranquilo", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_hello", label = "Hola", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "getsure_its_mine", label = "Es mio", category = "Gesture"},
    {dic = "mp_safehouse", anim = "lap_dance_girl", label = "Baile sensual", category = "Misc"},
    {dic = "gestures@f@standing@casual", anim = "gesture_me", label = "Yo", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_head_no", label = "No", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_no_way", label = "De ninguna forma", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_pleased", label = "Satisfecho", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_point", label = "Señalar", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_shrug_hard", label = "Ni idea", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_what_hard", label = "¿Que?", category = "Gesture"},
    {dic = "gestures@f@standing@casual", anim = "gesture_nod_yes_hard", label = "Si", category = "Gesture"},
    {dic = "anim@amb@business@coc@coc_packing_hi@", anim = "full_cycle_v1_pressoperator", label = "Barman", category = "Misc"},
    {dic = "missfam5_blackout", anim = "pass_out", label = "Desmayarse", category = "Misc"},
    {dic = "missfbi5ig_21", anim = "holdup_hallway_saw_player_scientist", label = "Asustarse", category = "Misc"},
    {dic = "missfbi5ig_36", anim = "_reaction_to_heli", label = "Ver un heli", category = "Misc"},
    {dic = "missheist_agency3astumble_getup", anim = "stumble_getup", label = "Levantarse desde suelo", category = "Misc"},
    {dic = "missfam5_blackout", anim = "vomit", label = "Vomitar", category = "Misc"},
    {dic = "missfam5_yoga", anim = "f_yogapose_a", label = "Postura de yoga", category = "Misc"},
	{dic = "anim@amb@nightclub@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_male^5", label = "Baile", category = "Bailes"},
	{dic = "missah_2_ext_altleadinout", anim = "sofa_loop", label = "Sentarse sofa", category = "Misc"},
	{dic = "amb@prop_human_bum_shopping_cart@male@base", anim = "base", label = "Apollarse en barra", category = "Misc"},
	{dic = "amb@prop_human_parking_meter@male@base", anim = "base", label = "Contando monedas", category = "Misc"},
	{dic = "mini@strip_club@idles@bouncer@base", anim = "base", label = "Esperando Seguridad", category = "Misc"},
	{dic = "mini@strip_club@idles@dj@base", anim = "base", label = "Baile del anunaki", category = "Misc"},
	{dic = "anim@mp_player_intincarnose_pickstd@ps@", anim = "idle_a", label = "Sacarse un moco", category = "Misc"},
	{dic = "anim@mp_player_intcelebrationmale@slow_clap", anim = "slow_clap", label = "Aplaudir Lento", category = "Misc"},
	{dic = "amb@world_human_prostitute@cokehead@base", anim = "base", label = "Impaciente", category = "Misc"},
	{dic = "amb@world_human_picnic@male@base", anim = "base", label = "Sentarse Picnic", category = "Misc"},
	{dic = "amb@medic@standing@tendtodead@base", anim = "base", label = "Buscar algo", category = "Misc"},
	{dic = "amb@code_human_cower@female@base", anim = "base", label = "Rehén", category = "Misc"},
    {dic = "amb@code_human_cower_stand@female@base", anim = "base", label = "Rehén de pie", category = "Misc"},
    {dic = "amb@code_human_cross_road@male@base", anim = "base", label = "Esperando", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@first_person@smoke@std@ds@base", anim = "enter", label = "Fumando", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@first_person@smoke@std@rps@base", anim = "enter", label = "Fumar pipa", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@fist_pump@low@base", anim = "idle_a", label = "Juego de manos", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@gang_sign_a@bodhi@rds@base", anim = "idle_a", label = "Hacer el capullo", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@gang_sign_b@std@ds@base", anim = "idle_a", label = "Avisasion", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@grab_crotch@std@ds@base", anim = "idle_a", label = "Rascar los cojones", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@nod@std@ds@base", anim = "nod_no_fp", label = "Vale ya", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@rock@std@rps@base", anim = "enter", label = "Cuernos", category = "Misc"},
    {dic = "amb@code_human_in_car_mp_actions@v_sign@bodhi@rps@base", anim = "idle_a", label = "Un doh", category = "Misc"},
}
--{dic = "", anim = "", label = "", category = "Misc"},

-- {scen = "", label = "", category = ""},
scens = {
    {scen = "PROP_HUMAN_SEAT_ARMCHAIR", label = "Sillon", category = "Sat"},
    {scen = "PROP_HUMAN_ATM", label = "ATM", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BAR", label = "Bar", category = "Sat"},
    {scen = "PROP_HUMAN_BBQ", label = "BBQ", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_BENCH", label = "Banco", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK", label = "Banco bebiendo", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER", label = "Banco bebiendo cerveza", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_BENCH_FOOD", label = "Banco comiendo", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS", label = "Press de banca", category = "Sat"},
    {scen = "WORLD_HUMAN_BINOCULARS", label = "Prismaticos", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BUS_STOP_WAIT", label = "Parada de autobus", category = "Sat"},
    {scen = "WORLD_HUMAN_CAR_PARK_ATTENDANT", label = "Agente de trafico", category = "Jobs"},
    {scen = "PROP_HUMAN_SEAT_CHAIR", label = "Silla", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK", label = "Silla bebiendo", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER", label = "Silla bebiendo cerveza", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_CHAIR_FOOD", label = "Silla comiendo", category = "Sat"},
    {scen = "WORLD_HUMAN_CHEERING", label = "Aplaudir", category = "Misc"},
    {scen = "WORLD_HUMAN_CLIPBOARD", label = "Portapapeles", category = "Jobs"},
    {scen = "WORLD_HUMAN_AA_COFFEE", label = "Cafe", category = "Drink"},
    {scen = "CODE_HUMAN_POLICE_CROWD_CONTROL", label = "Controlar multitud", category = "EMS"},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR", label = "Tumbona", category = "Sat"},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK", label = "Tumbona bebiendo", category = "Sat"},
    {scen = "WORLD_HUMAN_CONST_DRILL", label = "Taladro", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRINKING", label = "Beber", category = "Drink"},
    {scen = "WORLD_HUMAN_DRUG_DEALER", label = "Fumar porro", category = "Jobs"},
    {scen = "WORLD_HUMAN_MOBILE_FILM_SHOCKING", label = "Grabar con el movil", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FISHING", label = "Pescar", category = "Jobs"},
    {scen = "WORLD_HUMAN_MUSCLE_FLEX", label = "Mostrar musculos", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_FREEWAY", label = "Mendigo", category = "Misc"},
    {scen = "WORLD_HUMAN_GUARD_STAND", label = "Guarda de seguridad", category = "Jobs"},
    {scen = "WORLD_HUMAN_HAMMERING", label = "Martillo", category = "Jobs"},
    {scen = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", label = "Prostituta de lujo", category = "Jobs"},
    {scen = "WORLD_HUMAN_HUMAN_STATUE", label = "Estatua", category = "Jobs"},
    {scen = "WORLD_HUMAN_COP_IDLES", label = "Poli", category = "Jobs"},
    {scen = "WORLD_HUMAN_STAND_IMPATIENT", label = "Impaciente", category = "Misc"},
    {scen = "WORLD_HUMAN_JOG_STANDING", label = "Calentar", category = "Misc"},
    {scen = "WORLD_HUMAN_GARDENER_LEAF_BLOWER", label = "Soplador de hojas", category = "Jobs"},
    {scen = "WORLD_HUMAN_LEANING", label = "Apoyarse", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", label = "Prostituta barata", category = "Jobs"},
    {scen = "WORLD_HUMAN_VEHICLE_MECHANIC", label = "Mecanico", category = "Jobs"},
    {scen = "CODE_HUMAN_MEDIC_KNEEL", label = "Examinar", category = "EMS"},
    {scen = "CODE_HUMAN_MEDIC_TIME_OF_DEATH", label = "Anotar", category = "EMS"},
    {scen = "WORLD_HUMAN_TOURIST_MOBILE", label = "Selfie", category = "Misc"},
    {scen = "WORLD_HUMAN_MUSICIAN", label = "Musico", category = "Jobs"},
    {scen = "WORLD_HUMAN_PAPARAZZI", label = "Fotografo", category = "Jobs"},
    {scen = "WORLD_HUMAN_PARTYING", label = "Fiesta", category = "Hobby"},
    {scen = "WORLD_HUMAN_PICNIC", label = "Sentarse en el suelo", category = "Hobby"},
    {scen = "WORLD_HUMAN_GARDENER_PLANT", label = "Jardinero", category = "Jobs"},
    {scen = "CODE_HUMAN_POLICE_INVESTIGATE", label = "Investigar", category = "EMS"},
    {scen = "WORLD_HUMAN_PUSH_UPS", label = "Flexiones", category = "Hobby"},
    {scen = "WORLD_HUMAN_SECURITY_SHINE_TORCH", label = "Linterna", category = "Jobs"},
    {scen = "WORLD_HUMAN_SIT_UPS", label = "Abdominales", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_SLUMPED", label = "Tumbarse de lado", category = "Misc"},
    {scen = "WORLD_HUMAN_SMOKING", label = "Fumar", category = "Drink"},
    {scen = "WORLD_HUMAN_AA_SMOKE", label = "Fumar 1", category = "Drink"},
    {scen = "WORLD_HUMAN_SMOKING", label = "Fumar 2", category = "Drink"},
    {scen = "WORLD_HUMAN_SMOKING_POT", label = "Fumar maria", category = "Drink"},
    {scen = "WORLD_HUMAN_STAND_FIRE", label = "Calentarse en el fuego", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_MOBILE", label = "Movil", category = "Misc"},
    {scen = "WORLD_HUMAN_STUPOR", label = "Sentarse borracho", category = "Drink"},
    {scen = "WORLD_HUMAN_SUNBATHE", label = "Tumbarse bocabajo", category = "Hobby"},
    {scen = "WORLD_HUMAN_SUNBATHE_BACK", label = "Tumbarse bocarriba", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_SUNLOUNGER", label = "Hamaca", category = "Sat"},
    {scen = "CODE_HUMAN_MEDIC_TEND_TO_DEAD", label = "Examinar muerto", category = "EMS"},
    {scen = "WORLD_HUMAN_TENNIS_PLAYER", label = "Tenis", category = "Hobby"},
    {scen = "WORLD_HUMAN_TOURIST_MAP", label = "Mapa", category = "Misc"},
    {scen = "WORLD_HUMAN_STRIP_WATCH_STAND", label = "Ver stripper", category = "Hobby"},
    {scen = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", label = "Pesas", category = "Hobby"},
    {scen = "WORLD_HUMAN_WELDING", label = "Soplete", category = "Jobs"},
    {scen = "WORLD_HUMAN_YOGA", label = "Yoga", category = "Hobby"},
}
--{scen = "", label = "", category = "EMS"},
